clc;
clear all;
close all;
x=input('enter the input sequence');
h=input('enter the impulse sequence');
n1=length(x);
n2=length(h);
n=max(n1,n2);
y=cconv(x,h,n);
disp('press enter for input sequence');
k=1:1:n1;
subplot(221);
stem(k,x);
title('input sequence ');
xlabel('samples');
ylabel('amplitude');
grid on;
disp('press enter for impulse sequence');
k=1:1:n2;
subplot(222);
stem(k,h);
title('impulse sequence');
xlabel('samples');
ylabel('amplitude');
grid on;
disp('press enter for output sequence');
k=1:1:n;
subplot(223);
stem(k,y);
title('input sequence');
xlabel('samples');
ylabel('amplitude');
grid on;
