clc;
clear all;
close all;
N=input('size of the window:');
wc1=input('lower cut off frequency:');
wc2=input('upper cut off frequency:');
wc=[wc1+wc2];
h(firl(N-1,wc/pi,'stop',hamming(N)));
tf(h,l,l,'variable',z^-l);
freqz(h);
xlabel('frequency');
ylabel('magnitude');
title('Fir filter');
