tic;
clc;
clear all;
close all;
x=input('enter the input sequence:');
h=input('enter the impulse sequene:');
y=conv(x,h);
n1=length(x);
n2=length(h);
n=length(y);
disp('press enter for the input sequence');
k=0:1:n1-1;
subplot(311);
stem(k,x,'filled');
title ('input sequence','FontSize',14);
xlabel('samples');
ylabel('amplitude');
grid on;
disp('press enter for the impulse sequence');
k=0:1:n2-1;
subplot(312);
stem(k,h,'filled');
title ('impulse sequence - ','FontSize',14);
xlabel('samples');
ylabel('amplitude');
grid on;
disp('press enter for the impulse sequence');
k=0:1:n-1;
subplot(313);
stem(k,y,'filled');
title ('output sequence -' ,'FontSize',14);
disp(y);
xlabel('samples');
ylabel('amplitude');
grid on;
toc;